apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nimbus-operator-copilot
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ibrahim-2010/nimbus-retail-platform.git
    targetRevision: main
    path: Kubernetes-Manifests-file/operator-copilot
  destination:
    server: https://kubernetes.default.svc
    namespace: operator-copilot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
